### ISSUE TITLE
[BUG] TypeError for CBO when using Scikit-Learn 1.2.0

### ISSUE THREAD

**Issue by boydad** [deephyper/deephyper#168]
Deephyper 0.4.2 is not working with sklearn 1.2.0:
```
DEBUG:asyncio:Using selector: EpollSelector
INFO:deephyper.evaluator._subprocess:Subprocess Evaluator will execute run_mpi() from module base
Traceback (most recent call last):
  File "execute_dh.py", line 135, in <module>
    execute_deephyper()
  File "execute_dh.py", line 120, in execute_deephyper
    search = CBO(problem, evaluator)
  File "/lus/gila/projects/lqcdml_aesp_CNDA/.conda/envs/dh/lib/python3.8/site-packages/deephyper/search/hps/_cbo.py", line 186, in __init__
    base_estimator=self._get_surrogate_model(
  File "/lus/gila/projects/lqcdml_aesp_CNDA/.conda/envs/dh/lib/python3.8/site-packages/deephyper/search/hps/_cbo.py", line 343, in _get_surrogate_model
    surrogate = deephyper.skopt.learning.RandomForestRegressor(
  File "/lus/gila/projects/lqcdml_aesp_CNDA/.conda/envs/dh/lib/python3.8/site-packages/deephyper/skopt/learning/forest.py", line 234, in __init__
    super().__init__(
TypeError: __init__() missing 1 required positional argument: 'estimator'
```
Downgrading sklearn to 1.1.1 solves the problem.

**Comment by Deathn0t** [comment]
Fixed in https://github.com/deephyper/deephyper/commit/5ec919f9c1faf4d4357eec1558fa17cabfcceb5d
It will be released in `deephyper==0.5.0`.
